name: Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Clone repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 9
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: corepack enable
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: Run examples
        run: cd examples && npm run build

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@d774a4c7ebe335445d79c7b44138f56a76058ba0 # v19.0.0
        id: verify-changed-files
        with:
          files: examples/dist/main.css

      - name: Fail test if example file has changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: exit 1
